### ISSUE TITLE
Running testing scripts is not supported

### ISSUE THREAD

**Issue by gnuoy** [canonical/gomaasclient#102]
Running testing script (such as ntp, memtester, stress-ng etc) is not supported directly. It can be done via the deprecated API client with something like:

```
	values := make(url.Values)
	values.Add("testing_scripts", strings.Join(testScripts, ","))

	machine := new(entity.Machine)
	machineAPI := APIClient.GetSubObject("machines").GetSubObject(machineData.SystemID)
	err := machineAPI.Post("test", values, func(data []byte) error {
		return json.Unmarshal(data, machine)
	})

```

**Comment by skatsaounis** [comment]
Hi @gnuoy . Thank you for opening the issue. I am marking it as duplicate of #96, which includes the `op-test` implementation
