### ISSUE TITLE
API for logs of a Machine

### ISSUE THREAD

**Issue by vikramkrishna8814** [canonical/gomaasclient#103]
I'm looking for API for logs of machine. But i'm not able find the apis for that.

what api should we use to get the logs in the logs tab? which is in:
Machines -> {Machine_name} -> Logs

**Comment by skatsaounis** [comment]
Hi @vikramkrishna8814 ,

You can get the logs with [NodeResults](https://github.com/canonical/gomaasclient/blob/master/api/node_results.go#L7):

```go
params := entity.NodeResultParams{
    SystemID: "abcdef",
    ResultType: entity.INSTALLATION,
    // or
    // Name: []string{"/tmp/install.log"},
}
results, err := client.NodeResults.Get(&params)
if err != nil {
    return nil, err
}
if len(results) == 0 {
    return "", nil
}
data, err := base64.StdEncoding.DecodeString(results[0].Data)
if err != nil {
    return nil, err
}

return data, nil
```
