### ISSUE TITLE
Feature Request: Add LVM Interfaces

### ISSUE THREAD

**Issue by sempervictus** [canonical/gomaasclient#86]
The client supports RAID and BCache sets but does not seem to handle LVM (or ZFS) layouts. There are currently requests up on the TF provider issue tracker to handle these resources/data types which would first mandate implementation at this layer.

**Comment by skatsaounis** [comment]
Hi @sempervictus. It seems that to support LVM storage layout we are missing gomaasclient support for the following endpoints:

- DELETE /MAAS/api/2.0/nodes/{system_id}/volume-group/{id}/ -- Delete volume group
- GET /MAAS/api/2.0/nodes/{system_id}/volume-group/{id}/ -- Read a volume group
- PUT /MAAS/api/2.0/nodes/{system_id}/volume-group/{id}/ -- Update a volume group
- POST /MAAS/api/2.0/nodes/{system_id}/volume-group/{id}/op-create_logical_volume -- Create a logical volume
- POST /MAAS/api/2.0/nodes/{system_id}/volume-group/{id}/op-delete_logical_volume -- Delete a logical volume
- GET /MAAS/api/2.0/nodes/{system_id}/volume-groups/ -- List all volume groups
- POST /MAAS/api/2.0/nodes/{system_id}/volume-groups/ -- Create a volume group

As for ZFS, gomaasclient already supports:

- `BlockDevicePartitions.Create` to create a partition
- `BlockDevicePartition.Format` to format the partition with `fsType=zfsroot`
- `BlockDevicePartition.Mount` to mount the partition to e.g. `/` with `mountPoint=/`

I am using this issue to track the support for Volume Groups / Volume Group Logical Volumes

Thank you for opening it :slightly_smiling_face:
