### ISSUE TITLE
Query params for DNSResources Get()

### ISSUE THREAD

**Issue by arturshadnik** [canonical/gomaasclient#89]
Hello. Currently, the `Get()` method for [DNSResources](https://github.com/canonical/gomaasclient/blob/master/client/dns_resources.go) does not accept any query params but the [MAAS API docs](https://maas.io/docs/api) show that it should.

We want the ability to pass in query params (specifically `all: bool`) to retrieve the list of `entity.DNSResourceRecords` associated with each Resource. We've temporarily switched to using a forked repo with the desired changes, let me know if you would like me to open a PR with said changes.

This is similar to #67

**Comment by skatsaounis** [comment]
Hi @arturshadnik 

Thank you for opening this issue. Indeed, you can provide query parameters both to DNS resources and DNS resource records and it seems that gomaasclient does not allow you to do so.

PRs are very welcomed. Just be aware that before we can merge any incoming PR, the author needs to sign the Canonical CLA.

Signing the CLA is mandatory for contributing to Canonical's open source projects. Please see the details [here](https://ubuntu.com/legal/contributors).
